### PR TITLE
datatable fix for material ui

### LINKED ISSUE #2475: Material-UI Datatable doesn't populate columns
When using the datatable with Material-ui, the columns do not show up, however, rows show up and when the edit button is clicked, the proper data is populated there.

### PR DESCRIPTION
**Pull request by Neobii**
The `columns` in the data were not populating correctly so I grabbed https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-core/lib/modules/components/Datatable/DatatableContents.jsx#L9 from the core DatatableContents component.

Also I added getCollection so `collectionName` can be specified on the collections.

Fixes  #2475

### CODE REVIEW

File: packages/vulcan-ui-material/lib/components/core/Datatable.jsx [hunk 1]
```diff
@@ -132,14 +134,16 @@ class Datatable extends PureComponent {
...
+
+      const collection = this.props.collection || getCollection(this.props.collectionName);
 
       const listOptions = {
         collection: collection,
         ...options,
       };
 
-      const DatatableWithMulti = withMulti(listOptions)(Components.DatatableContents);
+      const DatatableWithMulti = compose(withMulti(listOptions))(Components.DatatableContents);
```
Comment (eric-burel) [inline packages/vulcan-ui-material/lib/components/core/Datatable.jsx]: Why the compose call hre?

Comment (Neobii) [reply packages/vulcan-ui-material/lib/components/core/Datatable.jsx]: I saw it here: https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-core/lib/modules/components/Datatable/Datatable.jsx#L219 so I decided to keep similar code style to the Datatable in core.

**Comment by eric-burel** [comment]
Merged, thanks!
